; common settings
Login=PLACEHOLDER_ACC
Password=PLACEHOLDER_PW
Server=PLACEHOLDER_SERVER
EnableNews=0
AutoConfiguration=true

; experts settings
ExpertsEnable=true
ExpertsDllImport=true
ExpertsExpImport=true
ExpertsTrades=true

; open chart and run expert and/or script
Symbol=XAUUSD
Period=H4
Template=Init.tpl
Expert=LumirMT4_v2